# Generated by Django 6.0.6 on 2026-06-27 04:26

import movies.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('trailer_url', models.URLField(validators=[movies.validators.validate_youtube_url])),
            ],
        ),
    ]
