# Generated by Django 6.0.6 on 2026-06-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.URLField(blank=True, help_text='Paste a direct image URL for the movie poster', null=True),
        ),
    ]
